### ISSUE TITLE
 Remain typo

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/game-project-scope-discussion#3]
Explain plans to reamin on track during project week.

**Comment by RealWeeks** [comment]
@Benjamski please clarify, I'm not sure what you mean.

**Comment by BenGitsCode** [comment]
Sorry, that wasn't clear at all. 

Under the Objectives heading, of the README the third bulleted list item says "Explain plans to reamin on track during project week." 

reamin should be remain.

**Comment by RealWeeks** [comment]
awesome, thank you

**Comment by payne-chris-r** [comment]
Fixed with bf8b5752841d3e70399585a1889690549ac60aa8
